name       : gst-plugins-ugly
version    : 0.10.19
release    : 15
source     :
    - http://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-0.10.19.tar.xz : 4934f65ff892637e7efaf1cfe635779189dde429d0706f40c86a3aac476ea873
license    :
    - GPL-2.0
    - LGPL-2.0
component  : multimedia.gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-0.10)
    - pkgconfig(libcdio)
    - pkgconfig(libmpeg2)
    - pkgconfig(x264)
    - lame-devel
    - libmad-devel
setup      : |
    %patch -p1 < $pkgfiles/cdio-cd-text-api.patch
    %configure
build      : |
    %make
install    : |
    %make_install
